service: sls-pandas-py

provider:
  name: aws
  runtime: python3.7
  region: ap-south-1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true

package:
  exclude:
    - '**/*'
  include:
    - '*.py'

functions:
  create_user:
    handler: create_user.create_user
    events:
      - http:
          path: create_user
          method: post
