service: sls-pandas-py

provider:
  name: aws
  runtime: python3.7
  region: ap-south-1

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true

package:
  exclude:
    - '**/*'
  include:
    - '*.py'
    - 'psycopg2'

functions:
  create_user:
    handler: handler.create_user
    events:
      - http:
          path: create_user
          method: post

  get_user:
    handler: handler.get_users
    events:
      - http:
          path: get_users
          method: get

  delete_user:
    handler: handler.delete_user
    events:
      - http:
          path: delete_user
          method: delete